.PHONY: clean All

All:
	@echo "----------Building project:[ RWA3 - Debug ]----------"
	@"$(MAKE)" -f  "RWA3.mk"
clean:
	@echo "----------Cleaning project:[ RWA3 - Debug ]----------"
	@"$(MAKE)" -f  "RWA3.mk" clean
